# Model Performance on test set

In [18]:
# select features with best performance on train set, in this case X_var_95
best_features = X1_var_5

# select the same features for the test set as X_var_95
columns_name= best_features.columns
X1_test_features = X1_test[columns_name[:]]
display(X1_test_features.head())
print(X1_test_features.shape)

,0,1,2,5,8,10,11,15,16,18,...,2032,2036,2037,2038,2040,2041,2042,2044,2046,2047
951,0,0,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,0,1
1059,0,0,0,1,1,0,1,0,0,0,...,0,0,1,0,0,0,0,0,0,1
1269,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
236,1,0,0,1,0,0,0,0,0,0,...,0,0,1,1,0,1,0,0,0,1
942,1,0,1,1,0,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,1

(286, 1308)

In [19]:
# apply rf to obtain performance of best feature combination on test set
rf = RandomForestClassifier(n_estimators = 100, random_state= 1)
rf.fit(best_features, y1_train)

#make predictions
y1_score = rf.predict(X1_test_features)
y1_pred_proba = rf.predict_proba(X1_test_features)[::,1]

# calculate performance matrices
print("=== Confusion Matrix ===")
CM = confusion_matrix(y1_test, y1_score)
print(CM)
print('\n')
print("=== Classification Report ===")
print(classification_report(y1_test, y1_score))
print('\n')
print("=== AUC Score ===")
print(roc_auc_score(y1_test, y1_pred_proba))

=== Confusion Matrix ===
[[221  13]
 [ 30  22]]


=== Classification Report ===
              precision    recall  f1-score   support

           0       0.88      0.94      0.91       234
           1       0.63      0.42      0.51        52

    accuracy                           0.85       286
   macro avg       0.75      0.68      0.71       286
weighted avg       0.83      0.85      0.84       286



=== AUC Score ===
0.7965154503616042

In [22]:
# apply rf algorithm to rank the features based on their importance
feature_imp = pd.Series(rf.feature_importances_,index=columns_name).sort_values(ascending=False)
feature_imp.head(10)

112     0.009179
2047    0.008740
1166    0.006373
1300    0.004789
633     0.004702
1455    0.004007
1217    0.003963
1391    0.003711
1316    0.003549
1303    0.003166
dtype: float64