# Model Performance on test set

In [79]:
# assigning column names as the 0% variance features
column_names = X_var_0.columns

In [80]:
# setting the test features as the fatures with 0% variance
X_test_features = X_test[column_names[:]]
X_test_features.head()

,AM1_E,AM1_Eele,AM1_HF,AM1_HOMO,AM1_IP,AM1_LUMO,AM1_dipole,ASA,ASA+,ASA-,...,2038,2039,2040,2041,2042,2043,2044,2045,2046,2047
951,-77978.922,-484111.81,-100.922530,-9.29992,9.29992,-0.82685,4.235959,518.88654,322.45627,196.43025,...,0,0,0,0,0,0,0,0,0,1
1059,-55631.867,-308149.69,89.680222,-8.61687,8.61687,-0.80911,4.261133,435.59259,224.47331,211.11928,...,0,0,0,0,0,0,0,0,0,1
1269,-56866.672,-277625.44,-150.823200,-10.08352,10.08352,0.94324,4.497928,393.40744,269.61371,123.79372,...,0,0,0,0,0,0,0,0,0,1
236,-112177.680,-799216.75,-15.559040,-8.43825,8.43825,-0.71327,1.242920,661.53381,406.86914,254.66469,...,1,0,0,1,0,0,0,0,0,1
942,-80280.555,-573363.69,-1.698020,-9.58055,9.58055,-1.28814,4.811505,461.10413,313.97968,141.15770,...,0,0,0,1,0,0,0,0,0,1

In [81]:
# apply rf to obtain performance of best feature combination on test set
rf = RandomForestClassifier(n_estimators = 100, random_state= 1)
rf.fit(X_var_0, y_train)

#make predictions
y_score = rf.predict(X_test_features)
y_pred_proba = rf.predict_proba(X_test_features)[::,1]

# calculate performance matrices
print("=== Confusion Matrix ===")
CM = confusion_matrix(y_test, y_score)
print(CM)
print('\n')
print("=== Classification Report ===")
print(classification_report(y_test, y_score))
print('\n')
print("=== AUC Score ===")
print(roc_auc_score(y_test, y_pred_proba))

=== Confusion Matrix ===
[[223  11]
 [ 29  23]]


=== Classification Report ===
              precision    recall  f1-score   support

           0       0.88      0.95      0.92       234
           1       0.68      0.44      0.53        52

    accuracy                           0.86       286
   macro avg       0.78      0.70      0.73       286
weighted avg       0.85      0.86      0.85       286



=== AUC Score ===
0.82836127547666

In [118]:
# apply rf algorithm to rank the features based on their importance
feature_imp = pd.Series(rf.feature_importances_,index=column_names).sort_values(ascending=False)
feature_imp_final = pd.DataFrame(data = feature_imp)
feature_imp_final.rename(columns = {0:'Gini Importance Index'}, inplace = True)

In [117]:
# display the first 5 values ranked highest on the gini imporance index
feature_imp_final.head()

                  Gini
a_nN          0.013407
GCUT_PEOE_0   0.011240
GCUT_SMR_1    0.007820
GCUT_SLOGP_0  0.007127
BCUT_SMR_1    0.005408

In [122]:
# export the list of features, and their gini importance index, to an excel file
feature_imp_final.to_excel(r'MD+RDKit5 Feature Importance.xlsx')